"use client";

import {
  Container,
  Title,
  Text,
  Stack,
  Divider,
  List,
  Anchor,
} from "@mantine/core";
import { Link } from "@/i18n/navigation";

/**
 * Юридический текст на английском как основной договорной язык (multi-jurisdiction).
 */
export default function TermsPage() {
  return (
    <Container size="md" py="xl">
      <Stack gap="lg">
        <div>
          <Title order={1} mb="xs">
            Terms of Service &amp; Disclaimer
          </Title>
          <Text size="sm" c="dimmed">
            Last updated: {new Date().toISOString().slice(0, 10)}
          </Text>
        </div>

        <Text size="sm">
          These Terms of Service and Disclaimer (&quot;Terms&quot;) govern your access
          to and use of the AutoScan website, applications, APIs, and related
          services (collectively, the &quot;Service&quot;) offered by the operator of
          the AutoScan brand (the &quot;Provider&quot;, &quot;we&quot;, &quot;us&quot;, or
          &quot;our&quot;). By accessing or using the Service, you agree to these Terms.
          If you do not agree, do not use the Service.
        </Text>

        <Divider />

        <section>
          <Title order={2} size="h3" mb="sm">
            1. Nature of the Service
          </Title>
          <Text size="sm">
            The Service is a software tool for vehicle on-board diagnostics (e.g.
            OBD-II read-only access, live data display, and optional AI-assisted
            interpretation of codes or symptoms). The Service is provided for
            informational and convenience purposes only. It is not a substitute for
            qualified automotive repair, inspection, or professional mechanical
            judgment.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            2. No Professional Advice; AI Limitations
          </Title>
          <Text size="sm" mb="xs">
            Any outputs generated by artificial intelligence, heuristics, or
            automated features (including DTC explanations, suggestions, or
            &quot;hints&quot;) are <strong>not</strong> professional advice, certified
            diagnostics, or safety assessments. AI outputs may be incomplete,
            outdated, or incorrect. You alone are responsible for verifying
            information, complying with manufacturer guidance, and deciding whether
            and how to operate, maintain, or repair a vehicle.
          </Text>
          <Text size="sm">
            <strong>
              You acknowledge that misuse of vehicle systems, incorrect repairs, or
              operating an unsafe vehicle can cause property damage, injury, or
              death.
            </strong>{" "}
            You assume all risks arising from your use of the Service and any
            reliance on its outputs.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            3. &quot;AS IS&quot; and Disclaimer of Warranties
          </Title>
          <Text size="sm" mb="xs">
            To the maximum extent permitted by applicable law, the Service is
            provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis, without
            warranties of any kind, whether express, implied, statutory, or
            otherwise, including implied warranties of merchantability, fitness for
            a particular purpose, title, quiet enjoyment, accuracy, or
            non-infringement.
          </Text>
          <Text size="sm">
            We do not warrant that the Service will be uninterrupted, error-free,
            secure, or free of harmful components, or that data (including live
            data) will be accurate or suitable for any purpose. Some jurisdictions do
            not allow certain warranty exclusions; in those jurisdictions, our
            warranties are limited to the minimum extent required by law.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            4. Limitation of Liability
          </Title>
          <Text size="sm" mb="xs">
            To the fullest extent permitted by applicable law, in no event shall the
            Provider, its affiliates, licensors, or their respective directors,
            officers, employees, or agents be liable for any indirect, incidental,
            special, consequential, exemplary, or punitive damages, or any loss of
            profits, revenue, data, goodwill, or other intangible losses, arising
            out of or related to your access to or use of (or inability to use) the
            Service, including damages related to vehicle operation, repair decisions,
            third-party hardware (e.g. adapters), or reliance on AI outputs—even if
            we have been advised of the possibility of such damages.
          </Text>
          <Text size="sm" mb="xs">
            To the fullest extent permitted by applicable law, our aggregate
            liability for any claims arising out of or relating to the Service shall
            not exceed the greater of (a) the amount you paid us for the Service in
            the twelve (12) months before the claim arose, or (b) one hundred U.S.
            dollars (USD 100), if you paid nothing.
          </Text>
          <Text size="sm">
            <strong>European Economic Area, United Kingdom, and Switzerland:</strong>{" "}
            Nothing in these Terms limits liability where such limitation is
            prohibited by mandatory law, including liability for death or personal
            injury caused by negligence, fraud, or fraudulent misrepresentation, or
            any other liability that cannot be excluded under applicable consumer
            protection law. If you are a consumer, you may have additional rights
            under local law.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            5. Indemnification
          </Title>
          <Text size="sm">
            You agree to defend, indemnify, and hold harmless the Provider and its
            affiliates, licensors, and personnel from and against any claims,
            liabilities, damages, losses, costs, and expenses (including reasonable
            attorneys&apos; fees) arising out of or related to your use of the
            Service, your violation of these Terms, your violation of third-party
            rights, or your vehicle-related activities undertaken in connection with
            the Service, except to the extent caused by our gross negligence or
            willful misconduct where such limitation is not permitted by law.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            6. User Obligations and Acceptable Use
          </Title>
          <Text size="sm" mb="xs">
            You agree not to:
          </Text>
          <List size="sm" spacing="xs" withPadding>
            <List.Item>
              Use the Service in violation of law or third-party rights.
            </List.Item>
            <List.Item>
              Attempt to gain unauthorized access to systems, data, or accounts.
            </List.Item>
            <List.Item>
              Reverse engineer, decompile, or disassemble the Service except where
              mandatory law allows.
            </List.Item>
            <List.Item>
              Interfere with or disrupt the Service or other users&apos; access.
            </List.Item>
            <List.Item>
              Use the Service in a manner that could damage a vehicle, endanger
              safety, or bypass manufacturer safety or emissions controls where
              prohibited.
            </List.Item>
          </List>
          <Text size="sm" mt="xs">
            You are solely responsible for ensuring that your use of diagnostics
            tools and data complies with applicable regulations in your jurisdiction.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            7. Third-Party Hardware and Software
          </Title>
          <Text size="sm">
            The Service may interoperate with third-party adapters, devices, or
            platforms. We are not responsible for third-party products, their
            performance, or their compliance with standards. Any third-party terms
            apply between you and the respective third party.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            8. Intellectual Property
          </Title>
          <Text size="sm">
            The Service, including software, branding, documentation, and content
            (excluding your data and third-party materials), is owned by the
            Provider or its licensors and is protected by intellectual property
            laws. Subject to these Terms, we grant you a limited, non-exclusive,
            non-transferable, revocable license to use the Service for personal or
            internal business purposes in accordance with your subscription or
            offering, as applicable.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            9. Privacy
          </Title>
          <Text size="sm">
            Our processing of personal data is described in our{" "}
            <Anchor component={Link} href="/marketing/privacy" underline="always">
              Privacy Policy
            </Anchor>
            . By using the Service, you acknowledge that you have reviewed that
            notice where required by applicable law.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            10. Subscriptions, Fees, and Taxes
          </Title>
          <Text size="sm">
            If you purchase paid features, fees, billing cycles, and cancellation
            terms will be presented at checkout or in order documentation. Taxes may
            apply. We may change pricing with reasonable notice where required by
            law.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            11. Suspension and Termination
          </Title>
          <Text size="sm">
            We may suspend or terminate access to the Service if you materially
            breach these Terms, create risk or legal exposure, or if we discontinue
            the Service. Provisions intended to survive termination (including
            disclaimers, limitations of liability, indemnity, governing law, and
            dispute resolution) will survive.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            12. Governing Law (EU/EEA/UK and US)
          </Title>
          <Text size="sm" mb="xs">
            If you are located in the European Economic Area, the United Kingdom, or
            Switzerland, these Terms are governed by the laws of{" "}
            <strong>Ireland</strong>, without regard to conflict-of-law principles,
            and the courts of Ireland shall have non-exclusive jurisdiction, except
            that if you are a consumer resident in another EEA country, you may also
            benefit from mandatory protections and venues of your country of
            residence.
          </Text>
          <Text size="sm">
            If you are located in the United States or access the Service from the
            United States, these Terms are governed by the laws of the{" "}
            <strong>State of Delaware</strong>, without regard to conflict-of-law
            principles, subject to the arbitration and class-action waiver below and
            any non-waivable rights under US federal or state consumer law.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            13. Dispute Resolution; Arbitration (United States)
          </Title>
          <Text size="sm" mb="xs">
            <strong>EU/EEA/UK consumers:</strong> You may have the right to use
            out-of-court dispute resolution, including the EU Online Dispute
            Resolution platform where applicable. Nothing in these Terms limits
            mandatory consumer rights.
          </Text>
          <Text size="sm" mb="xs">
            <strong>United States:</strong> Except for claims that qualify for small
            claims court or seek only injunctive relief for intellectual property, you
            and the Provider agree to resolve disputes exclusively by binding
            arbitration administered by the American Arbitration Association under
            its Consumer Arbitration Rules, except as modified here.{" "}
            <strong>
              YOU AND THE PROVIDER WAIVE ANY RIGHT TO A JURY TRIAL AND TO PARTICIPATE
              IN A CLASS ACTION OR REPRESENTATIVE PROCEEDING
            </strong>
            , to the fullest extent permitted by law. If this class-action waiver is
            held unenforceable, the arbitration provision shall not apply and
            disputes shall be brought in the state or federal courts located in
            Delaware. You may opt out of arbitration within thirty (30) days of
            first accepting these Terms by sending a written notice to the contact
            method described in Section 16 with your name and a clear statement of
            opt-out.
          </Text>
          <Text size="sm">
            If you are not located in the United States and mandatory law prohibits
            arbitration for consumers, the foregoing arbitration clause does not apply
            to you.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            14. Export and Sanctions
          </Title>
          <Text size="sm">
            You represent that you are not located in a country subject to embargo
            or sanctions, or designated on any restricted party list, and that you
            will not use the Service in violation of export control or sanctions
            laws.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            15. Changes
          </Title>
          <Text size="sm">
            We may update these Terms from time to time. We will post the updated
            Terms and update the &quot;Last updated&quot; date. If changes are material
            and required by law, we will provide additional notice. Continued use
            after the effective date constitutes acceptance of the revised Terms,
            except where prohibited by law.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            16. Contact
          </Title>
          <Text size="sm">
            For questions about these Terms, contact us through the{" "}
            <Anchor component={Link} href="/marketing/contacts" underline="always">
              contacts
            </Anchor>{" "}
            page on this website. Do not send sensitive personal or vehicle
            identification information unless we explicitly request it through a
            secure channel.
          </Text>
        </section>

        <section>
          <Title order={2} size="h3" mb="sm">
            17. Severability
          </Title>
          <Text size="sm">
            If any provision of these Terms is held invalid or unenforceable, the
            remaining provisions will remain in full force and effect.
          </Text>
        </section>

        <Divider />

        <Text size="xs" c="dimmed">
          These Terms are provided for informational purposes and do not constitute
          legal advice. You may wish to consult qualified counsel for your specific
          situation.
        </Text>
      </Stack>
    </Container>
  );
}
